FROM ubuntu:20.04

COPY /Rakuten/requirements.txt /

RUN apt-get update && apt-get install python3-pip -y && pip install --no-cache-dir -r /requirements.txt
RUN python3 -m nltk.downloader stopwords

VOLUME /rakuten

WORKDIR /rakuten

EXPOSE 8000:8000

CMD uvicorn api_rak:app --port 8000 --reload --host 0.0.0.0