FROM apache/airflow:latest

ENV MY_DOCKER_PATH=/opt/airflow/rakuten

COPY /requirements.txt /

RUN pip install --no-cache-dir -r /requirements.txt
RUN python3 -m nltk.downloader stopwords

ADD /Pipeline_prediction.py /opt/airflow/
ADD /Mongodb_connect.py /opt/airflow/

VOLUME /opt/airflow/rakuten

EXPOSE 7000:7000