FROM apache/airflow:2.6.1

ENV MY_DOCKER_PATH=/opt/airflow/rakuten

COPY /requirements.txt /

RUN pip install --no-cache-dir -r /requirements.txt
RUN python3 -m nltk.downloader stopwords

ADD /Pipeline_entrainement.py /opt/airflow/dags
ADD /Mongodb_connect.py /opt/airflow/dags
ADD /dag_airflow.py /opt/airflow/dags

VOLUME /opt/airflow/rakuten
