name: Python package

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 -m nltk.downloader stopwords
    - name: launch API
      run: uvicorn api_rak:app --port 8000 --reload --host 0.0.0.0 &
      env: |
        MONGODB_LOG:${{ secrets.MONGODB_LOG }}
        MONGODB_PW:${{ secrets.MONGODB_PW }}
        MONGODB_DB_NAME:${{ env.MONGODB_DB_NAME }}
        MONGODB_DB_COL_USERS:${{ env.MONGODB_DB_COL_USERS }}
        MONGODB_DB_COL_LOGS:${{ env.MONGODB_DB_COL_LOGS }}
    - name: Tests with pytest
      run: |
        pytest
